
package derms.replica1.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DERMSServerService", targetNamespace = "http://replica1.derms/", wsdlLocation = "http://localhost:8387/ws/derms?wsdl")
public class DERMSServerService
    extends Service
{

    private final static URL DERMSSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException DERMSSERVERSERVICE_EXCEPTION;
    private final static QName DERMSSERVERSERVICE_QNAME = new QName("http://replica1.derms/", "DERMSServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8387/ws/derms?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DERMSSERVERSERVICE_WSDL_LOCATION = url;
        DERMSSERVERSERVICE_EXCEPTION = e;
    }

    public DERMSServerService() {
        super(__getWsdlLocation(), DERMSSERVERSERVICE_QNAME);
    }

    public DERMSServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DERMSSERVERSERVICE_QNAME, features);
    }

    public DERMSServerService(URL wsdlLocation) {
        super(wsdlLocation, DERMSSERVERSERVICE_QNAME);
    }

    public DERMSServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DERMSSERVERSERVICE_QNAME, features);
    }

    public DERMSServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DERMSServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DERMSInterface
     */
    @WebEndpoint(name = "DERMSServerPort")
    public DERMSInterface getDERMSServerPort() {
        return super.getPort(new QName("http://replica1.derms/", "DERMSServerPort"), DERMSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DERMSInterface
     */
    @WebEndpoint(name = "DERMSServerPort")
    public DERMSInterface getDERMSServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://replica1.derms/", "DERMSServerPort"), DERMSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DERMSSERVERSERVICE_EXCEPTION!= null) {
            throw DERMSSERVERSERVICE_EXCEPTION;
        }
        return DERMSSERVERSERVICE_WSDL_LOCATION;
    }

}
