
package derms.replica1.jaxws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DERMSInterface", targetNamespace = "http://replica1.derms/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DERMSInterface {


    /**
     * 
     * @param duration
     * @param resourceID
     * @param resourceName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addResource", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.AddResource")
    @ResponseWrapper(localName = "addResourceResponse", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.AddResourceResponse")
    @Action(input = "http://replica1.derms/DERMSInterface/addResourceRequest", output = "http://replica1.derms/DERMSInterface/addResourceResponse")
    public String addResource(
        @WebParam(name = "resourceID", targetNamespace = "")
        String resourceID,
        @WebParam(name = "resourceName", targetNamespace = "")
        String resourceName,
        @WebParam(name = "duration", targetNamespace = "")
        int duration);

    /**
     * 
     * @param duration
     * @param resourceID
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeResource", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.RemoveResource")
    @ResponseWrapper(localName = "removeResourceResponse", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.RemoveResourceResponse")
    @Action(input = "http://replica1.derms/DERMSInterface/removeResourceRequest", output = "http://replica1.derms/DERMSInterface/removeResourceResponse")
    public String removeResource(
        @WebParam(name = "resourceID", targetNamespace = "")
        String resourceID,
        @WebParam(name = "duration", targetNamespace = "")
        int duration);

    /**
     * 
     * @param resourceName
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listResourceAvailability", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.ListResourceAvailability")
    @ResponseWrapper(localName = "listResourceAvailabilityResponse", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.ListResourceAvailabilityResponse")
    @Action(input = "http://replica1.derms/DERMSInterface/listResourceAvailabilityRequest", output = "http://replica1.derms/DERMSInterface/listResourceAvailabilityResponse")
    public List<String> listResourceAvailability(
        @WebParam(name = "resourceName", targetNamespace = "")
        String resourceName);

    /**
     * 
     * @param duration
     * @param resourceID
     * @param coordinatorID
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "requestResource", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.RequestResource")
    @ResponseWrapper(localName = "requestResourceResponse", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.RequestResourceResponse")
    @Action(input = "http://replica1.derms/DERMSInterface/requestResourceRequest", output = "http://replica1.derms/DERMSInterface/requestResourceResponse")
    public String requestResource(
        @WebParam(name = "coordinatorID", targetNamespace = "")
        String coordinatorID,
        @WebParam(name = "resourceID", targetNamespace = "")
        String resourceID,
        @WebParam(name = "duration", targetNamespace = "")
        int duration);

    /**
     * 
     * @param resourceID
     * @param coordinatorID
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnResource", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.ReturnResource")
    @ResponseWrapper(localName = "returnResourceResponse", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.ReturnResourceResponse")
    @Action(input = "http://replica1.derms/DERMSInterface/returnResourceRequest", output = "http://replica1.derms/DERMSInterface/returnResourceResponse")
    public String returnResource(
        @WebParam(name = "coordinatorID", targetNamespace = "")
        String coordinatorID,
        @WebParam(name = "resourceID", targetNamespace = "")
        String resourceID);

    /**
     * 
     * @param oldResourceID
     * @param newResourceID
     * @param coordinatorID
     * @param oldResourceType
     * @param newResourceType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "swapResource", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.SwapResource")
    @ResponseWrapper(localName = "swapResourceResponse", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.SwapResourceResponse")
    @Action(input = "http://replica1.derms/DERMSInterface/swapResourceRequest", output = "http://replica1.derms/DERMSInterface/swapResourceResponse")
    public String swapResource(
        @WebParam(name = "coordinatorID", targetNamespace = "")
        String coordinatorID,
        @WebParam(name = "oldResourceID", targetNamespace = "")
        String oldResourceID,
        @WebParam(name = "oldResourceType", targetNamespace = "")
        String oldResourceType,
        @WebParam(name = "newResourceID", targetNamespace = "")
        String newResourceID,
        @WebParam(name = "newResourceType", targetNamespace = "")
        String newResourceType);

    /**
     * 
     * @param coordinatorID
     * @param resourceName
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findResource", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.FindResource")
    @ResponseWrapper(localName = "findResourceResponse", targetNamespace = "http://replica1.derms/", className = "derms.replica1.jaxws.FindResourceResponse")
    @Action(input = "http://replica1.derms/DERMSInterface/findResourceRequest", output = "http://replica1.derms/DERMSInterface/findResourceResponse")
    public List<String> findResource(
        @WebParam(name = "coordinatorID", targetNamespace = "")
        String coordinatorID,
        @WebParam(name = "resourceName", targetNamespace = "")
        String resourceName);

}
